<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="Personajes.xsl"?>
<!DOCTYPE personajes
[
	<!ELEMENT personajes (personaje*)>
		<!ELEMENT personaje (imagen, nombre, altura, peso, pelo, lugar)>
			<!ELEMENT imagen (#PCDATA)>
			<!ELEMENT nombre (#PCDATA)>
			<!ELEMENT altura (#PCDATA)>
			<!ELEMENT peso (#PCDATA)>
			<!ELEMENT pelo (#PCDATA)>
			<!ELEMENT lugar (#PCDATA)>
			
				<!ATTLIST pelo color CDATA #REQUIRED>
				
]>

<personajes>
	<personaje>
		<imagen>data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMSEhUUExMWFhUXFhoaGBcYGBoXGBcXFxcYGBgXGBgYHSggGBolHRcYITEhJSkrLi4uGCAzODMtNygtLisBCgoKDg0OGxAQGi0iHyYuKy0tLSstLSstLTUtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSsrLSstK//AABEIARwAsgMBIgACEQEDEQH/xAAcAAEAAQUBAQAAAAAAAAAAAAAABgMEBQcIAgH/xAA8EAABAwEFBgQEBAYCAgMAAAABAAIDEQQFEiExBhNBUWFxByKBkTJSobFCYsHRFCNy4fDxQ5IzgiSisv/EABkBAQADAQEAAAAAAAAAAAAAAAABAgMEBf/EACIRAQEAAgICAgIDAAAAAAAAAAABAhEDIRIxQVETIgRhcf/aAAwDAQACEQMRAD8A3iiIgIiICIiAiIgKmZM6daKnaXZs7/osZd8Ugaccm8BdXMUcASKDLhRQnTNorG6XuLKOzLSRXnQkforwOrXopQ9IiICIiAiIgIi8vfTvwCD0iBUpbQ1pAOp0HH/XVBVREQEREBERAREQfCVG7n2mD3StndHG5krmsGIeZgpRxrpxWavau5kpWuB1Ka1pwXNdvmkL3Fkhc6pqHZVNdAeGazzysvTbiwmUu2+3W7fWh26cCIm4Qa+R0j86ZakNH1V7YpWtaXmgq6gy4VoAPZczWXa+22eXA17ogXglnU0BI7inst53ztA0QQuNABEJXcgSMLG9y4n2U763VfHd1Ej2dtgk3hBy3sgHo85rKBhxk1yoMvdar2VvN43IrSjnO/7nQ+5Ww9n7bvg9/wCYD1DW6dNUwzmS3NxXCsuiIrsRERARFjb7vUQNyze7JreqCrbbcGubG3OR2gHDqeQVxDHTU1PE/tyCwFxDCXPccT6VlkOjeOAH7q+bee+IbDqRUuIyY06GnFx4D3QXlptNDgZm/WnBo5u5duK+2WyhtSTiedXHU9ByHRLHA1gLWkk6uJzJPMnmrhrQEBF9RAREBQEREFOdriKNdhOWdK8c8iqi+Eqzvp7xBIY/jDaj0zp66IRabQ2l0cbnteG+VzRUVAJFcfoKrn6+bA2TA6KU4x5aUqRQnzPp+J1a+oUit23z31gtPwuJoWg1YfhoebdCoZfNlljkfNZpC5upplUdly55XKu3jw8J3No/fbpN8N6PM2gy0IB1Cld1OmljaXSF0QpXP5NAeOVcu6i1undOWmlKD3qs1ckrmCjgB1xEZdAMvdWz34yK8Fk5LfhNbnvL+azgAamnIDJbZ2LjpC/rIc+dAAfstGWNhDQ/MZ5d65ZrYUu1Asl3MMUg37Hglh/HU+YEcqcVHDe238ubks+W0UUG2V8QmW926bA8OIzIIIGWZrwFeKl1i3mKQPw4Q4COla4cDa4idTir6LpefZZ7XaIrK9LaImVqK9dABqSiHq87e2Bhe49hzPJQKyNkttoL3OwtHxO0DRXIDqvNrtMlunEbTRoGvBrRq49VgNoNot44WC76lhOFzh8Uz60IDuDRxKDPXner7VILJYv/AADIubrKeOZ/AOfHsM5fct3iztEbM3Zbx/AdB1/2VZbM7PiyRiNhxTOA3knBo5Dl0HqpLBCGCg/2eZ5lB7AX1EQEREEV2jtsr7VFZY3YA9pc53bgOZopLZoQxoaCTTicyVjrbcwktEU1fg1HXhRZZE0RERDzLGHAg6FfXNqKL6iCCXl4W2SaTeF0gqc2gilDwBpVWV9+GcWCllkcw4T5HHEHU66grZC8vOSrcIv55fbkG84N2cq00048l6uywTTOOHKgqcRp9OK2xt5dELQ2rGtLI61GReXOOvP+5Ws4bS6N5JYfNTDw45ehWPle5HRJj1fisrDjjaGSGoOflrSozpXsvm0jS81ikc6OlIw7VraVLa9DkqM8k0+GNjDXFnloDlWvLqvN7QzQ0Y9uTQRUZio1UY3Tp1j8rrYOCZ1oijixVJGLCSMq1JJHLVdE3tejbKyMuDnY3sjAGZLnGg/dcwXBtDPZX7yB1DSh4gjkV0Bs9bH3hd0JY/A/EwOecz5HDHh5E0Iqt44uWevpLDNRrnO8oFePAcei1rtLfT7RJhHw4gABxzyCy+21/wBKxMOQyJ5n9gte2+9NyMTT5+HT83f9lZgvtqb1Fkj/AIaJ38yTOdwzI5RCnHms94cbMCyt3sgraZMmt+QakelfMewWD8OLjE8httpzYxx3YP8AyP4vNdQDl37La1jhbEDI/Jx0HyjXCPuTzQZCzwho5k5k8zxKqrBTXsHuwMdVxzNNGN5nmeQWVscQaMqnqdT3UbTpcIiKUCIiDEXVfET5JIMY3sbjVvHCTUEc8isuohtXsUy0yCdkhhlaD5m8aDKqv9h7wknsrXS/GCWk/NTQqFrJrcSBEVreU2BmKtKObXsXAH7qVV0ipslxNxN4ioX1j86HkCg9rG3/ACYbLOS7D/LeAeRLSB9SsktX7c7XMk3sTX0iaSx2HV7hqK8AFFukxrm870mhgjZLK2UsiwZg6cATXMjmozY7c+W0MDz/AGoMlbXpJvJSWkluKgFVRuuUsnDxq0k9KDUKlx6taYZW2NzxWeGCxPZiDZHgeY6l1K0B6EqGT2qaSOksZwtcayCmHr9aq5tFp3pBccqVqSQ3PPVoNFgb9v4mPcNP8sGtK1rT834hlkVyceNt07eTKYxaWuzNLmhmVdey3Ldtuhuy7ozC4STShjaYvhxEkmg0oCVoGMmR5weVoGtdOvdZOxSbtuXoOOZ16LtmOnDlyy/DY1ttlavdmBr/AJzJUfsVmfbrSIm5A5vPysqBl1OgHZWc14udE2MmrhqeZ681tXwz2Z3LA5//AJJPM7mBwHoD7uPJWZpTdVhigaGkAMZGCAdBQkV+n35qNbRX857sq14NGetKZcXLKbU25rXlg+FrcxzDcw33Kj2w1m/iLW+V/wAMQxf+xrh+xKyyy3dR0cfHrG51MdlrmdCMUg87hUnkeJPXh2CkoCo2NxLQTqc6cgdAgno/AdSKt6ga+y0k0wuXldq6IilAiIg8yCoI5hUrLZ2xMDWigCroQgpslrksTtDbACyLi9wNOTWEOcT7fVUL0tO5ns9Dk57mOHTCSD6EKM7V3wBPLJwY0QsPDE/OQ+jaquV0vhjbUq2ZtL5N4SfIMAaOuHE7/wDQHosNtFt/BZ7SLN5t46jQSKMa5xFDX1zVTZu2YI2lxDaNfLJnpi+EO60P2WsttYRaJyXGj24A2T85biofoouWot+O21tfaW/hBA5rXVf5WB35nCp9aZ+oWlr6ueBrpjJK9wc8lrRlQ0zqe9VQt9/zEMbIc2PLiObqjM+wHYLDWqZ1ptIjc8hjiXOIyPMgJvZljMZP7YWF7WyZA4RXD36r3ZiN7Ti4GvTkFnNpJLMxrGQRhrhqeJWNuu6pHHeU8o0NeKe4idPTb2tEREUbi4DgM6AqyjhEmIu8uenLmSspYrdHHvPn4+nBWloeJHE0oPxH7N7phNfCOTK/anZQ1rD8tfeiouvKn/HQfVXd3WN88giiaXEa8h76BZ+8NiJYmF0lMxwFQFOXJjj7Rjx5ZTqLrYC6GT2lj3uGBpD310GHQGutaaLf9wReUynV+g+Vg0B66k9StE3JFJYhETGLVGHtfRuTqtHwkUzW4Lq2r/ibPI/+HkhpGXDHShBBAoR1r7KZlLNw8LOqhG0VqrvX1zfI4D+kFZ7YcNZY6mv86SlRyBoB00Kgd8z0YOxP1IU72PkBskTKVwOYT6tLvu4Ln4+8tu/mx8eKRP7vdWNvYfZWbrBI61tmLxu2RlrWCtS5xFXO4cKKzff0NmjaHEudQANYMRJWQsFqllo5zN23UB3xHuOC6Xn6sZBERECIiAvhNEJWB2nvsQ2Vz21q44GcKnmOmRRMm7pr7a2/8NsY4FwDHZ14HOuXY0VD+OMpoQCWgEaH+bO/GSOoYB7rDWKIzzPr5qkNpqTjdQ/YqrclphiNpxOAwuO7J1Hnwk98LaeqwvbumMxx2mN3sa6zy1NN5IGuNdGVxOz7BRq87rdNZLRKwGgmL2u54cqU1rSqoXltIxsLI45AQQ8v5VdUDrWn3VOGeS0wRwtdgBAFWk0JIcRipzr9FFOO92yotf7d5CyQfFhLSfSoPfVRm1TOaWOb8XD/AD1UjvWF8Ldy8UcCSR1JLfsD7qOW6XDJESMhQ+zv7K/H1GHLjLdz08Ps8hfiean/ADgsnbb5McTYwKEDQ/dXd6YJJW7vMPPtzVxet1aPOfcKv5ZuSl4erYilnH4iKnh1cdPZX0kjWUbwaMTzzeeH1X20SNBLgPKwZdXFY6zy5kOFcQz+5W7mbL2ELIYxIRQvOI9OSkd9bQMlZgH+lArstYEYFeFP2K8TWstz5rgstyu3pY6mMZuy2/dPBBpU1H9X+1tie+GTWASs/wCWmLoWjzN+n1WiLI9z5Gmlc8h+qnWz0zoY9w4+QuOXylwAJ7UV8b4dI5MPPVRy/pqCnUj2/wBrPsvKVu7gs9S9zGYgMs8Iy704qMbQGsgb1J9z/ZSDYKStoe52obk486GqnB0cs/Tbaux9wblm8mIkmeAS4j4BT4GcgpKrO6Zw+JpHKivF1vIt3RERECIiDCbWW/dRNFabyRsZPRx830qoX4qzGMwRDJjWEjlwH2U52nuYWuB0WLCci13yuGhWsdrrovHch1pwPZCcIePiLXUzPTIZlVybcOtxG9nra+MvewgOa5jqEVBoXD9fqsJfU4a4g61J9Saq6sEzmOcOBFPUGo/VRa/rS/euPVVwx2t/I5MpfFQtVtOlFc3Le01mcJWSYSDUAireVSCrCzyggucNPqTw/X0VnPIXV5LS9ubGaSHaS+XSyl7j5nkE8tAdPUrE3jKHgOrnSipWsFwDugr3Gv0oV7uljS8B/wANdFEi1zutM1stG4HG7QDKuSyF/wB9ktwVAA/VULxvDAK8BwGnQKK221mRxJ9Ao8JvZ+TKzx+Hm0Wkuy/DXIfqriyObUl30ViGqu1xAyVkMjDaXfC00HCvLkpNBZDK1tcmgivX9lCWyHspXc98YW0ePKR29Vz8uN1uOriznqs5FYi2sgFMByHTiVmrfaAGsk4kCvdYC77XJMTgFWVp/V0Cu72hfG3C7INFaLn7vVde5e4s71j/AJ/QtBb2PD3UouiCaz2b+WzEZiWtyq4EEAu7ZrC3JFv3wtc7WRoryBILvop3dVpdJa42YQ7EASflBLn4umgC245tTm5P10m+ytikhs7WzGsmZdyBPAdlUt9sJnjs4qMYc5x/K2mQ6kkZq/ssRYxrScRAzPM81DdrrU6C8bA8aSOdGR0NP3+i6a8+TyqbNFMl9RFKoiIgKnNC17S1wqCKEHQhVEQat2m8OzG2R9nOJuZwH4x/SeIC0ffpe19HN04rsJat8S/Doz4p7KPMfjj59W9eiiTScr5e2gXkGEcM6n3I/ZWRkpor60Wd8RdFI0tcCcnCh60qrVsDTlip3yUoerPLqCdfvwKpvaWmumf15L6IW/MPTNXe9aC0OzyA4cDkUHq0uxNFdNT3WNYM+ivJ8GdHEjgOqqiwnDVxDRy4ptC1JC+V5FJWfKSQvcDHu0IH0UnS8ggFKnOug781sq4Ng22mIjE5r2sxucc2taRWNtNQ4/ERXitbWO2Oie0yM3jQ4EjQkA1pXquhvDW97LarHIyF5M7g58wIIcHPqB/6gANHQBRe043V6QOJrLIwVpRg93c1gDapLUXyE4Yxx4uPIKttA10jhCa0aTi9CRT6L7bJGxRsjFANfVcWtPSl3/i82RaWTt5NcXCvRhKnmxMhktD3tFS1kYA0zEYOfq5QG7pQ04uBa/6scP2Ww/C+UY5i4itGAnhQRsWvEy5cf122Dd9qbKwSN4jPoRqD1BqrW23S2WeKV+YiOJg/MQRX2JUb2Xvh38daIDSjnFwAyoQczTqKKbrocdlgiIiBERAREQEREED8WNl4rTZJJSwbyNuLEBnQa59lzRbLAWuAbV1dBTNdmW2zCWN8btHNLT2IoteTeG0Udrs72gui0cOLTQ0PYn7oOfG3JJuy45U4HXJWEw81F0L4qbGMEQnhGEtoHAZAj9StH3hYS2ajwKa1HLWqpLd6q9xmtx6uqwkCobV7tPyjmVmBdgArJ53f/Udgr65oQ1oqMzn7/wBlkbXZssuKttTSGXgzPQeixjqhSO2QkE1UfteRorM9dq9nZvBh/Fw/Zbh8D7jkgjmt0go1zMDAdThdm7tXJaeuhpxA8l0T4c2wz3U5nGIvb6Vxj6GiVae2sb9tJdLLIKNL3F1OAzUQvG1OkeMWgUkvo0c4ci5Q61PpX2XPjN1vc8te0oNqIDXU8tAB/nZT3w3lG+eHuowRNe49gBRauuybesYzR2dOWXNTTw9JNtbG/IYTiHMMGIDtkok1dOzG+fDdpJs9imvcyN8pL3OI5N0p7Lb6gnh5cb45J5pBm40a7mKkkjpop2t5HFyXdERFLMREQEREBERAREQal8d2yUszg94jx0Ib8JdXLEOIWn7zskm9Jc4aaAZU9V1Vb7thtQAlYHhj6gEZYm/daJ8XNmzBawYmkRuZir65j0/VZ5b3tpherESu28MhnWmvopZdU+8aTQYaDDzKhlz3bK+ZscUbnvccmjUdTyHVSqzRPgkwSDCRkVb2zqwvyCmihdrNStiXrECCtf25vmPdWit9qlzzhrsJ0P3XRPgrZiLE9x0fM6nZoDf0XNbAcTQOYW6PCbaLcTiCR3kmyA4Nk4HpXT2U0+WC8R7mdZLU9pILX1e06ZOJq09qrXN5ii6N8Y7jEtmM4+KIa9CudrZZi41xaeiz1qrraw2wxuB68FNbjvp4tMc0YOIHKvHIih91Gbuja2tW1dzKmWwl0/xNrjjdiDTU1A4gZUqqZd118VmOO7XQdwPLoWvcaue0OPTLQLJKhYrK2JjWN0aKBV1s5KIiIgREQEREBERAREQeZHhoJcQABUk5AAcStLeI16m0yYoz5ACG6+ZoJqW86uyyWytsbK+dkcDXBjJZAJCT5i0ZlrRxJAPsvo2aa18RidgY0jE3CHFwb8DKn4WjM0HEquWPlNLYZeN2jvhFsybNA6aRp30pqcTaFjB8LRX3V14jbMslhM8bQJGZmn4m8QeqnCo2yziRjmHRwI91Mitcz3rbKMyzyUFtMhc4lbL232dlsjnNOYNS13AhawkJxUPNTELuxPAPVZyw2xwcHVoQcjyI0KwUJbRXdjlFac1NRp05ctqZel20cc3sLJOjxx+x9VrlvhJa8ZbijwVNHB2dDzFNVV8HL83c+5c7yy5U5SAVHuMvZbsVLjtpjnY0XsTspaYbTgks1Y64JA5lWOZXM14U1qFte5NkrLZHl8LCHHma07V0WdRJjpOWdoiIrKCIiAiIgIiICIiAvEZrn7L5IeHP7JNJhY52uFpNOwqgtryu1s2Eklrm1wub8Ta5GldCRlXqrxgoAFitl7ZNNAJZmhrnklrQCMLPwg14rLICIiCI+Jt2tmsTyR5ozjae2o9lzDtBZMD6jQrrXa2LFY5x+Q/QLmHaGKrev7IIqx9FVbKclb0X1pQS7Z+8XMe1zTQggjoRmCuodnb0Fqs8cw/EMxycMiPdcm3YOK3x4MXoHMlhLswQ9o6EAOp6gINmIiICIiAiIgIiICIiAiKlaH0FOeSC3tL8Ic/OpoB9gPcr1Y4wAG1JIAqeZVs55dMGjSMAu/qd8I9BU+oWSZkM/VB9QFfHHOi9ICIiCja4cbHMP4mke4ouZtpbtfFI+KQUc1xH1yPYrp9as8Z7tad1KBRzqtd1AzCDnm3Q4XK2Wd2laAQBqsGEGUuhxoeinWwN6Ps8zZG8HCo+Zp+Iey1/dczWmh4kLZ2yOzsz3MnhwvjErQ8DN0ZqCHFvFhyzCDoCyztkY17TVrgCD0KqrxE2gGQHQaL2gIiICIiAiIgIiICxNutzQ91Tkxuf3P6D1VxfVt3MTn+g7lazZbS5xq44pXgYfmBdUk+1PVBsK4W4o9474pHGQ9jkwejQ1ZN8g0PKqpQuws0pSgA6/wC15jJcQaanj8rf3KC4jbx4lVERAREQFAPFqyPfFE5rS4NJrTrQD30U/XiSMOycAeOYrmNEHLl73MTUPbhcDQg6gjUKKT3aWuOYpr3FV0N4sWZsLGSsjb/MkAkdTOlNa81pe+jGKgHTT1zVMs9XTTHDc2xUULTUUAFKg8iOqmnhjtEYbdFmQ1xEbgNHNcRSvUEqGWYOcNaDpqslsXH/APNhFf8AkbT/ALhR32ZTp1qi+BfVozEREBERAREQERfCghPiNb6BkVfzH7D9VArnrJa4hmQ12Kg/LwV1tBeT5Z5C52Khdhy4A0H2VnsTKDbAHaGvqRmB6kBBts2vAxjMw80oDmcTjQV9an0WVg4mvQemv1qoa62iW1xAZiPHIeu7BjbX/wBsamVlFGgdKnudUFZERAREQEREEG8X5Q2w6jEZGNAOpqcwOq56veJ1ST81KHkKAeq3p4unB/CyPFYmyOr0c5jgwn1K0vfFoY97nDjX3GmXossrZk1wm8VlCde6zPh7AH3jAOG8b7g1/RYUEUoTTSv+c1JtmMMdrgkb8Jc2vQgj903pNlsdMtX1U4D5Qqi1YiIiAiIgIiICsb6tQigkcTSjTTuRkr5RjxAc8WV2FtW1q7t1HJBp+2S0xGpqTRYqx3mYJQ9uoKurbJkB6rD2qInPgiWyfCi2meWYyZuIYwcg0F0h9a5+q27Hx6UH0XPHhjef8PbW4icDg4Gh0NK1p2BHqugrDO2Rpc3QuPu04T9QiFyiIgIiICpzzNY0ucQANSdFUUa2+tjorOC1oNZG1roAKn7gKuV1Npk3UO8R74htTNwKmrgW01Lq5Ho3utZG4YjPgdLiAzkIyaPyj1WSttutAnMxDG5O6g1FFG22ubFIIwXGSlQGl2nKi58fPLt174sVWyXXHK6ejThZkCD+Lgrq5Yt3FG4k4nPBDag6HL6VWIhs1oBcKPaXnMEFtTwyIU+8PthpnyAyscG61pQgcvNTXmtLhWd5Mfr7b2u59YmHmxp+iuVELZf8kTyxhZgZQU3ckhFBShdEaDsQqsG17CQHPjj4netfFUflxarZzpUitbHeUMorFKx/9Lg77K6QEREBERAVG22ZsrHRu+FwIPqqyINF7X7G2izyuLGukiDSWuArlydTQqz2L2cltkpY5rmNwk4yMq0yGeufJdAUXyiDUsXh4GWo/wAO40ifEHF2nmbikplnkR/2W0LqsQgibGDXDXOgFakmtBxzV1RfUBERAREQF4lia4UcARyIqPqvaIMcbis1a7iKv9A/ZXcNkjZ8DGt7NA+yrIgpSWdjviY09wD91VoiILOe7InHEWDF8w8p9wrW13I2TU4x8kgD2+lcx7rLIgi79i7M1xcxjGHmGkU7UIVzZbme34ZpGU4h+8a7u14NPdZ48ljnXTG0lzC6M/kdQHu3T6ILiyufXC81IGtKV65K6VKzOJaCcyqqAiIg/9k=</imagen>
		<nombre>Akuma</nombre>
		<altura>178</altura>		
		<peso>80</peso>
		<pelo color="rojo"></pelo>
		<lugar>Japon</lugar>
	</personaje>
		<personaje>
		<imagen>data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITEhUSExMWFRUXFxgXFhgXFxgZFxcaFR8WFhgYFRoaHSggGBslGxUVITIiJSkrLi8uHR8zODMtOCgtLisBCgoKDg0OGxAQGy0lICYtNS83Ly0vLS0uLS0tLS0tLS0vLS0tLS0tLS8tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAPAA0gMBIgACEQEDEQH/xAAcAAEAAgIDAQAAAAAAAAAAAAAABQYEBwEDCAL/xABBEAACAQIEBAQDBgQDBgcAAAABAgADEQQSITEFBkFREyJhcQeBoRQyQpGxwSNS0fBicpIIFjNT4fEVNENEgrLS/8QAGQEBAAMBAQAAAAAAAAAAAAAAAAIDBAEF/8QAJhEAAgICAgAGAwEBAAAAAAAAAAECEQMhEjEEEyJBUWEysfChkf/aAAwDAQACEQMRAD8A3jERAEREAREQBERAEREAREQBERAEREAREQBERAE661QKpZiAoBJJNgANSSegAmJxPitOgLvfa+gudJVcVx3DY/Nh6lMtTvqhOjZbE+IAddenpISmkTjByK3jfjBUOIalhsKlRMxCMztmcDdgoXyr89pc+T+bUxS5ajUkrBiMivfN18oOvy9JrHmfhmFw1V0o/wAJL2dRoDmAI829jqLekjcN9nYrTRrsTZQL7/31lXmO7LfLVHom85mrMRiMXgMKlcY0tTAAyNTBAzfykklhr6S68mcxLjsKuIUZSSyMvZkNjb0OhHoZbCfIqnDiT0Ti85kyAiIgCIiAIiIAiIgCIiAIidVarl6EnoB/ekA7CZ0HFpr5hpqdekrfEuI1XYqLdgo1APdj+K2nYe8+ahWlRvUYlAMzk7sSdF+egyiYp+Kp1FGhYNW2TtPjNFtnG9v2merXlKeuhDtUYKRowvpSFswX/ORZj11AklwriOVqdM2PiaH0cZrggddBf3jH4lt1JHZ4UlcSyxOBOZtMwmLjsYKYF7XYhVF7XJnXicZ0XU9+kr/NFTLTWqTqjqRf/EQp/r8pXKddFkcd9mHzLiqT1PCqVQrgXtaw7Df9LzW2AVsNiSpbOHbxEJ0zgnUW/KSfxC4mhPi3uLKDYb9/1mvOM8bXE5Ey2VNi25J9OwlSTey9tRosfP3F1LrRWzOVsxvmA810v62IHykLwCq61srgXynUDUDY/mDb5yGpZE1W1/QTu4dxTw3Je5BGX1GoN/paS46pFblbtmyefeaUq4JKapZsyAg2sQD0t/lMmfhUPCB8Oo5DIHdLjwlLEBcq6kta1zpNO8Z4t4xCroo79Tt8h/1l+5GxT0nFLCo9erYBrEkWO5cbKO17dJymkdtOzb/+8yjQobjfUbxMZOXnYBmyBjqw10J1I/OJO5EKgWmIiWlQiIgCIiAIiIAiIgCQPNvFPBonKfO3lUdSTpp8zJ0ync4YREBezVcTW/h0Qfw73KKNBYXN/rK8t8XRZiSclZX24sKQVL3OrVD1IH4R3ZiLexmLnfHMKXiWdGDsTfJnXWmgsdQhsTbqBrITF6XQkg5SCV3W4I+faSnJVRbqwOmY66jW/wC8xY4Ls2zZzg+D4yiz4cquISkr1abVCfFU5WJTQEPmKizG1tBrMn4Z4lsRial6bU6dMB1DNnbOxDFmIFrt+8y+dj4tKoMyoyhrKKjLUqBQdRlNhcXsCG+XSO4BxypQQ1kRWqViKNFGJAy0beJVYjXKtyPUiaKXbM+3pG3ryM4jjNfDW2oux9P5R6mRNbF+QVK1UXYXCqbKL6iw6+5kLg+LjwsRWBtZsiX6mwsf1MnLJekRhjrbJjEY3z+Gm4F3bog7Eyi898e8R/BQ/wAOmPmzHdj9PrOK/GBRpZb3JJZu7MevsNAPb1lLxTVazkU0Z6jbKovb/EewHcyKRO6FUgo5c5s3l8xuLDp7CVLEYcZiEIsCbfsR/fSWvjXAsRSpI1SwQaGx1B7P7232vpKpXNm8pv2MlF/BCf2dSU+7XPYf1nc9OpplX00GpvMrhFJmcAC5Y2UAXYnsoGpPtN//AA45N+zoMRiEAxDfdU2PhL/+zqT2vaS23RDSRqHlz4Z8RxZUtTNGmd3qi1h3CfeP0nonlzglLB4enh6IsiC1+rHcs3dibmSQE5k0qIN2LRETpwREQBERAEREAREQBERAEjuMLanUqKmeoKbqgA8xLDRQelyBJGcWnGrQRqbj/AHw6UabMrNWcmqR1bTKi9cqi9z3N+ulSwtLEIr1KL2VajDKRobWvbtczbXONGlTXxmF6rlUDHUqi3fKnYXFzbe81pWxANFKS7+ao7dBnLED18v6zNJcHo2Y7yIx35lxldfBqJTNMixJHyv7zIwy1KuIWjTF2WiidlVbsdew0JPckyOTEqvmANhovqZYuUeKrh6Nasx89Qg269gB6AAfWRUrf0XSgoR12YfNNOrhhkNZW62C233G95EYXihyUla1g5qN2uO/5To5kxrOQ7HzG5t2A2kEpyoGc3LfdXoAdie977dJNLRRJ7M7i3FQzkjUk2A6fOWn4Ziz1C33jYE+nb0AlK4dhmqHNuToth+gHUmbW5N5Cr2LVyaKkaKLeIT67hRbpufSSlG1SIKVbZiHlytxF8RTSoEpAZSXBYZiDlCgW7A3vppJXAfBXh6oBVatVewzNnKAnrZVtYX6S+8H4VSw1Pw6S2F7m5uWJ/ExO50H5TPlkI8UVTlydkPwHlnCYNcuHoqndt3Pux1Ml7TmJMgIiIAiIgCIiAIiIAiIgCIiAIiIAkFzbzLSwNHxagZiWCoi2zOx2AuQB6k7SbYzRvF8Y2OxzOzXSncIOi5r2A7eWx9yZCc+JZjx8jA4nxOti8QK+Ie75SqU1uKdKmTcqP5mOl30vYaCRuNxf/pptpmPf0klxXDgsWRvKFyljp729JH4JKakuxAUfibqfTvMsm5M9DFjcVXR2GmVQs2lgT7Tr4fU+7mOgGgkXxvj+dilL7lrFiNWPXToJH0K7jUb/p7ScYUtkc005en2JPjWILuVXcix9Ad5iCgFZc1z3Jnbh8QgFr+pPUn1nTj8YDp9JYjK9lr+F+NP/i1FBbLlqA6X3RyCD0Pl+pHWehFmgPg9wmpXx/2hQFp0fO53uSrIiD/UT8vW43+snAry1aOYiJMrEREAREQBERAEREAREQBERAOLzgNNQ/E/mGsOI08JTrZKQoguuti9QuQbDV7Ko021MlH4rVdKwNQVkWkXYqKlBkOwJXNoR6NbSVyycXRZHG5KzZYM5lA+EXMD18K1OtULVKdTIpdru6FVqLcnViAWF/SX+TTsg1RG8yYvwcJiK3/LoVX/ANCM37TzfwTi5UObXubnvqAP0Anojmqk1bB4qhT1epQrU17ZnRlUE7DUieVrVKLtTdSjoSrK2hUjcESE0pFuKTiWbiHETUtbyqNgf3kNiQ9Q6nN2A2HsOk7sFQqVvKo079pKuKWHQ5fM+1/XsO8p66NruauXRAVMKU1ayj1nYroRowNux2mBxOuznzH2A2F+/cz5SjYAMcgPS31PWWqPyZXl36VolKTXHl2nBpknv3/vpIunVAOVCbdf+kksBjKYIRwVUkXYWLEdd9L2vvIyTROEkz0H8KOG0qXD6T0wc1Xz1CerC62HZRawH9Zc5C8nDDDB0RhbmgFslzc7m+a/4s17+t5NS5dGWXbERE6REREAREQBERAEREAREQBODOqpikUgMyqWNlBIBJ7C+51H5ztJgHnn4iYpqfGK1RiEUFFLEebJlT7vfe/ykTzNxnx6aU6NaoXv5s2XzKA3VQNDpobzdPPXw7w3EvOzNSrhcq1FFxYXIFRD98Ak9QfWac478KOKYY5qaDEKL2akbN11KNY/kTK3C3ZbHJSorGArZSWOhvoeo0tp20PSXXk7mkUFfN4jZ2AJFRgbIAFXW+gJb85QeLcMxdG3j0atG9wpqIyBrb2JFjad/AjmHh5Sz3JAUEsRa5Nhrpa/trOSjaEJUzZXEeOpV8yCpTbofGd/obAfISjcwVzWrZz5nChWN73IJtf5ETlMZl8qkFjoBv8AOdmGWux/4hHogAH6SFcTRH16/v2ff20U6Soulxr895D4ytmNzsNpZhh6trGvUHs1/wBRMKtw+t0rX9HRSPzAvIxkkXTxyar+/ZAUT/INf5jqfl2nVUYAEMCGPXff9ZI1qGVwroEJ0DoTa50F1Mxm4ewY5vPb+Xp7jcS20ZXGfQw1UKgBQfXWY9atfpaZqU0G6A/nefVWjSYWVbHvFocZV2bp/wBn6opwNUCo7MK5zI1stO4BBp+jA3PqDp1O0hNBfBLj1PCV6tCs4RKwUqzEBc6XFiTtcNp7TfaOCLjUb3G3uJYjPJUz6iInTgiIgCIiAIiIAiIgCR3HuLU8LQqV6n3UF7dWP4VX1JsPnPrjnFqWFoviKzZURbnqT2VR1JNgBPN/Gebq+MrPiMQx8NLtTo5v4aHUADYFrWBa3e1r2gGDzbxupiarPXs9Q731CAm4SnfZR9d5J8ofE7GYEqhP2igNPDqMcwHanU1K+xuJ98r/AAxx+O/iOPAptr4lUG7X1utO9z87S2J8BiP/AH6n3wx+v8eOwXngnxN4ZiKef7QtE/iSqQjqe3Yj1BIkzwzmjBYh/DoYmlUf+VXGY9dBudO01i/wYrIpKYmg7WOUGg63PQZvFNvexmsU5SxzYxsKKL/aVa5GxXYipmGgXUENf21g6ehudOcqWEtQWkcTiKgstBeobT+IbGwOoAsb2PS5lJ5hw3ExTLvSwvDaLDK32cBsQ+bamClmYnsCo01IE45fwdPgxbxMuKx9QFmYHy0QbaO5uzOxuTsSO256zxariahr1jmKghF2Vb75R++/rKZ5lE1YPCyybekVvA8rqP4jDwqdhYEhnI9bAAE+g/Pc9+IxlOmMtNQOl+p9zJfiFcBcz6+glQ4rxoDyqqovpqT7mZlJzez0nCGGNLRJ4UrWQhDlYelz7gfiF5F18Y9FstZNPwuv3T7g6j2kNgcU61FdSRc6TK4jxypUurBbe28s4NP6KPOUo70zJxVVaoVd0cFfZhqPnrIZMVlfJVJBXTONTbpcdR9Z84TE5SQNtDbtlIIP6zu5rwhFRXH4l+ov+0mtOimT5Ll8EuyItI1WYOoFwR1PQe97SvYOqc49RMfD3sVva/5EiZ/DqPmu2hAOnrJJUQlLm1SJXlngr4zF08Kmmc+c/wAtNdXb8tB6kT0Zypy+uBpNQSo70s16Qc3NNSqgqD2Lh27DNbpNC/C3ifhcSouLZWfwT7VRl3/zZD8p6WAlkTPlOYiJIqEREAREQBERAE4aczhhAKBzNhW4riaeFQsMJh3ZsTUU2D1QLLRTuVuST0J7iS3D+QOH0q/2hKAz6EBiWVSPxKpuAx77yzpTA2AGt/mZ9wDicxOCYBzKLzzzNVw9YUqYCAoD4hAJa5Isva2upvvt3tHFON0cPlFVrFr5QBcm25sOg7zXvxL4nSrml4ZzZA1zbTz5SAL/AOU+15TllSpPZq8Libmm42v8KolAuXYXZmuxv1J3N+9zJPDUivk7DX3M+OGgJSLdToJ9061lqMemv5TC3Z7kUlTInj+OsfD/ABWJI7Af9przDUzXqkn7oMnq2J81V2P4W/MzG4VgilE1G8t72v8ASaoLijzc03kl9GG9UCppst7fKRNSqTf30ndWq3JCzIwmCd3SjSUvVqMFUDck9B29z0lpkbsxE8ot1O/pLfxqnnprbfJnX/42v+sqWIwlSlUenWRqdRTZlcEMD0uD+ssNTHg0qTD8O/taxEhNbRbhkqaMCvhQ1PxU0U6Mv8rf0kcca6gpobi1+omXXQqWA2P1HSYOTW8miuT2ZvLeLyVVG1mVh7qQR+gnsBGuAe+v5zyHwLhfjY2hQ28Wsim+1mIv9Lz15TQAADYAAewk4opyPpH1ERJFYiIgCIiAIiIAiIgCIiAcMdJrbjPxTVGZaFAVB+B2qFQ3+LIFvl7ai8+PiBzu6V2wNI5PKBVqE2Y5xotP+XfVj3sLbzVuK4ZWepbw26AWFwANreglE8m6RsweHTjykrLdWxtWoj4uprVewPQKi3yqo6KLk/OQrYlnteTPB6hymm42W+vpvO7CYWiPOpAHr+0yN7tnqKFpJaR14akxABFuw/czA43jlpr4CHNUc2sNhfue95YcZrSc0h5spI9Ta9pSeC8IdqgqP0Nx7jW5iCTtsZnJVGPuKXDqVFS9Ygnc9tOg7yqcd44+IayjKg0VfTvJHmrEZ6pS/lU9NpXW9Ntv6zVBe7POzTr0x6/ZfPhByjSx9ep46lqNOnc2LL53PksykWIAY/Obf5W5M4ZhcS74cZq9PQh6hdqWcA6A/dJB3313lF5JwmJwuEprRq5alY+KVFrkuFVcxOlgoGhPc9ZFcxcxOvEkxNN8lc01FQD7q1ad6bKejU3VUNv3tLOaM/ltujv/ANoelbF4Z/5qDD/S9xfv9+ay4ZiNSjbEfWXX4p80Lj1wblMlWmKyVV3Hm8IoVPUGzeoII9TSaWHB1/SJUxC4umZtdvKAdxp8ukxUXrMlsxGUjWc+FYhOv9ZxdE3tk7ythmPE8BkF2NakfkhzOfkgJnqETSvwb4IamKfFm2SgGpr3L1AtyO1k/wDvN1CTh0U5fyEREkViIiAIiIAiIgCJwTMDF8TVWFNfPVIJCA7AdXIvkX1PyBgEhecEyHx3FDhqPiV8rOTYLTBAJNyFXN2G5NtjoJTeMcy1qqENamh/Cp1I/wATHUj0FpVPLGHZow+Fnl2uvk6+P16K1sX4ANapilCVXaxFNQMmSlpqOttge/SIGGygZnsbbbmQ5avWzZG8Kgv332uPSd+BwT1hamClHufvP6k9pkm3J2z1MSjjVR/78nbj8aiqwU3cjKfQe8iuG0qjN5QSOvaZGLxeEoki5ruNMtO2QHsWOn6n0mHU5rqWsKAQf4HufqonVB1pHXmhfqkWSrikw9Mmo1vTv6CUjjXMT1Logyqe25mNxPF+Ibkkk7el+h9Z24bBinSfEOLkCyX7/wBZ2MFHbK8mVzdR0ivYtMpynfczK5awlOriaa1b+Fcs9hqVQElR/mNlv0zXkZWcu5Y+3zln5QwTM1RqYzOP4aDqSRmbKADc7e2pmnpHnfky/DjjVKn/AAyEp2ZvCUk0E2zEgdtdexlD5upKuLZs6vTrWdHUkgMdCpuLgg2OvQieh+U+CjC4WnRIXPbNVI2ao2rse/b2Fpqj418vUKJSrTBTMwBXKfDJN9abDRW7od9COs55dBZbZrni6EgX1PfvI4DSZa12IynoJi1hadivY7N27R90sW69SZn4emWqDKCzEgKBuzMQFHuSRIWo2oE3H8E+XVq1XxlQXFEhad9vEIuW9Sqkf6p1o4pUrZszkTl0YHCLRvdyTUqnu72vb0ACqPRRLFOBOZYUN2IiIOCIiAIiIAiIgELxvjXgq1kaowByqu7N0X895E/D/hWIRKuJxZP2jEMCwJ0SmmbwqYA0UDO5tv5tZZUwKBiwGpNzrpfuB0nbXew032F+5h0E3VFY5yAc01voly3e5sFH5X+kgBwQOc1byqNkG5Hr2ltrYZA3iVGGhsvZDsSe7EkfSaa5z52xVStSTDXpioqGmgF6reIxFMsdszDKQttLgHWZpYnKXI9DH4iMIKBcOYq2Go0hUr2SimqUwPvnobfiM1FzTztXxN0W9KjtkU6sP8Z/aZXxHwWIo10+14tcTXKZnCknwL28h6XOuwG3qJmcG+FeKqUvtWKIw2HC5zfzVSvQKmlmN9LnqJOONLsqyeIclS0jE5U4YXpr0B8x+Zk7xPApTTTeWrl7lp8ihV8NLbtrYDe2xa3fSQvGsMKlY06V2sbAnrbUn0H9JHlbOcaiUtqJQ5tCN7H9JjcZ4vUqhaZyhb3AUEWtoOsleJixK9pWwPEe67DQfuZOl2c8yX43o7+GYN6tanh6K53Zgq26sevoAAST0AM9O8o8p4fA0USmimoqgPVsM7ndiTvqSZp34OmnR4jTVx5qiOqE75rZvqFaeggJOJTP4Fpj47BU61NqVVA6OMrKwupB7gzJiSIGlecfhC6Fq2AOZdT4DHzD0pOTZh0Cn8+g1RjaDKxRlKspsysLMpHQg9dp62xdeorUwlPOGaztmC+Gtic1j97WwsO81bzLyvieLYs5sIuC8FmR8SxNQ16Y/wCHkUZQx3Ou2mu4kWicZ/JpzhvCqleulGkpd3NlVRcnufQDqTpPUXJPAxgsHSw+mYAtUI2LuSzn8zb2AnVyjydheHqwoKS72z1HN3a3S/QdbCwlitOpCUr0cxETpAREQBERAEREAREQD5ZhKVx/mpQCUIFEGzVTexIufDw4GtarpqQQq9yb2+uIYz7VXq4dmAo0rhqak56jDLpUP8tj93bYm+w7cPylRrMKmJGZgtkoqbJSTogy2PTXYG3pJVStkOVukVXgWMfiVKqKwqUSuIy0alEktTA8GqQWcEEh8utu+1pP4T4d4elQdcITRxDG32ph4lZbm7lb2yki+1t5b8BgqVBBSpIqKNlXQa6/rPqrjUV1QmzMbDfU72nHsklRQeEfCHCUMYMUalSqinOtKoA3n/ndzq+tzqN+9pY+Mfxqy0zY06P8Rwdc7/gFuoX7x9SvaWNiLSnYFiRUqf8AMe4PpckfrKckqVF2KNuzp5q4j4VCw+8+ny6/noPzlOwtDwqFSu33iMq/Pc/tM7mLE+NiMo2Wyj37/nedfNVZFoijpmW1+ltD/WULZqqkUj/dfHY6nUqYWlnUPkbzBSSRchL72BF/efPB/hLxapcmktG2n8SoAT7Zc2k9Bcq4VaeEoIq5AKam3W7AFifUkkyXmpIxN7NR8ifCrEYbGUsXiK9M+EWKogZixZWTVmtYAMTpfabcERJERERAEREAREQBERAEREAREQBERAEREAqNfFlsYz2PhquQHUkvTN2IX8QsSu+6yewOBVXarlAZrX7kDv8A0n1T4ZTFQ1QvnItckmwuTYX2FyTYTNAk3LVFcYbtnTXpj71hmA0v/frOmnhlYh9b6EjcAzJrVAoJYgAC5JIAA7knaVqvzB4rGnhtvxVjouvRO59f16VykorZbGDk9HdzNxEW8BHGd2VGtuM3/e8wMFVvUCDRVsB9JjHh3hstz5lDP6sX8pc6+46zIweHemKjBSzdFFr+gOuneZJycmbIKMYlMwmIUO1RjcK2a3cg5rfSVajiga6PWF0NVWqi51XMC9+puLzOx5NKtVQ6WY/3rIGub37W/sSyKorySs9OoO23SfUw+DoRQpK24poDfuFAMzJoMwiIgCIiAIiIAiIgCIiAIiIAiIgCIiAIiIAnTiq6ojOxsqgsT2A1JndK/wA44bE1KGTDqrXNqis2XMhB0v2va/pecfR1FM5w5lHiqjfxATmFO+anZdVzAfePXX5SvDmqqKjOiBVAHlUlRv0/X5T6x/IXEKTAimK2YA3pkWU9V1sbCfVPk/ieX/y5Hpmp3/WVcSzmiFxHGqhc1FuLqwPmJJzdCemusnMBznVRcqGmgO91uT0uTfU+sxsRy5jkBL4NyOuUBvopJkLU4bUGpoVU/wA1N1/UTqX0HL7O/jOOfEVQ5sWIANha5F7abXtYflNk8nfDoUHFfEstSoLFEA8iEa3JP32B20AHrK9yHyq9aqtWorLTQhrsCM5XUKt9x3Py66bhEmkQbOYiJIiIiIAiIgCIiAIiIAiIgCIiAIiIAiIgCIiAf//Z</imagen>
		<nombre>Ken</nombre>
		<altura>178</altura>		
		<peso>75</peso>
		<pelo color="rubio"></pelo>
		<lugar>EEUU</lugar>
	</personaje>
		<personaje>
		<imagen>https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSK3Py6OzeXudG_oYBlJq-JTJUe-bbTRDKsBJ1VNCET4Ncu5ZLs</imagen>
		<nombre>Guile</nombre>
		<altura>185</altura>		
		<peso>86</peso>
		<pelo color="rubio"></pelo>
		<lugar>EEUU</lugar>
	</personaje>
		<personaje>